services:
  web:
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      DJANGO_DEBUG: "true"
    ports: []

volumes:
  postgres-data:
    name: tanu-postgres-data
